#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

if [ ! -f ./run/.env ]; then
    exit 0
fi

set -a
. ./run/.env
set +a

if [ -z $MAISON_DMX_CONSUL_ADDRESS ]; then
    exit 0
fi

address="$MAISON_DMX_CONSUL_ADDRESS:8500"
api_root="http://$address/v1"
./vendor/wait-for-it "$address"
curl -f -X PUT --header "X-Consul-Token: $MAISON_DMX_CONSUL_TOKEN" "$api_root/agent/service/deregister/ola"
curl -f -X PUT --header "X-Consul-Token: $MAISON_DMX_CONSUL_TOKEN" "$api_root/agent/reload"
