#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

. ./.env

target=/etc/udev/rules.d/maison-ola-ftdi.rules
new_rules=$(docker run --entrypoint /bin/cat "bartfeenstra/ola:$MAISON_DMX_OLA_IMAGE_VERSION" /etc/udev/rules.d/ftdi.rules)
if [ ! -f "$target" ] ||  [ "$(cat "$target")" != "$new_rules" ]; then
    ./vendor/krab/bin/krab stdio-inform "Updating udev rules in $target..."
    sudo bash -c "echo '$new_rules' > '$target'"
fi
